config/routes.rb
Rails.application.routes.draw do

  namespace :tab do
    get "wand"
  end
  namespace :board do
    get "mirror"
  end
  
  namespace :magic do
    get "home"
    get "sensing"
    get "gestures"
    get "light"
    get "mirror_portal"
    get "wand_portal"
  end

  root 'application#index'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index
    
  end
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  def mirror
  end
end

app/controllers/magic_controller.rb
class MagicController < ApplicationController
  def home
  end
  
  def orientation
  end
  
  def gestures
  end
  
  def light
  end
  
  def portal
  end
  
end

app/controllers/tab_controller.rb
class TabController < ApplicationController
  def wand
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/magic_helper.rb
module MagicHelper
end

app/helpers/tab_helper.rb
module TabHelper
end

app/views/application/_back_to_root.html.haml
:scss
    #back-button{
        position: absolute;
        z-index: 100;
        top: 15px;
        left: 15px;
    }
    
= link_to root_path, id: "back-button", class: "btn btn-primary" do
    %span.glyphicon.glyphicon-chevron-left

app/views/application/index.html.haml
.container-fluid.np
    .col-xs-12.col-sm-6.np
        .panel.panel-primary
            .panel-heading 
                %b
                    Practicum 4
                Mirror, mirror
            .panel-body
                %ul.list-group
                    %li.list-group-item 
                        = link_to magic_sensing_path do
                            %b #1
                            Orientation and Motion APIs
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                    %li.list-group-item 
                        = link_to magic_gestures_path do
                            %b #2
                            Gesture Recognizer
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                    %li.list-group-item 
                        = link_to magic_light_path do
                            %b #3
                            Light Detector
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                    %li.list-group-item 
                        = link_to magic_mirror_portal_path do
                            %b #4
                            Portal - Mirror
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                    %li.list-group-item 
                        = link_to magic_wand_portal_path do
                            %b #4
                            Portal - Wand
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                    %li.list-group-item 
                        = link_to board_mirror_path do
                            %b #5
                            Magic Mirror UI
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                    %li.list-group-item 
                        = link_to tab_wand_path do
                            %b #6
                            Magic Wand UI
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                   
            .panel-footer
                CS160 - Intro to UI Design and Development
   

app/views/board/mirror.html.haml
#mirror
    #webcam-feed.col-xs-12
        %span MIRROR, MIRROR
      
// IGNORE, BUT KEEP THIS LINE (Back button)   
= render :partial => "application/back_to_root"

:scss
    #mirror{
        height: 100%;
        width: 100%;
        color: white;
        font-family: Avenir, sans-serif;
        font-size: 4em;
        text-align: center;
            
        #webcam-feed{
            height: 100%;
            background: desaturate(blue, 80%);
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
        }
       
    }
   

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Workspace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    - controller = params[:controller]
    - if controller != 'application'
      = stylesheet_link_tag    controller, media: 'all', 'data-turbolinks-track' => true
      = javascript_include_tag controller, 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{name:"viewport", content: "user-scalable=no, width=device-width, initial-scale=1"}

  %body
    = yield

app/views/magic/gestures.html.haml
:coffeescript
    $ ->
        console.log "BIND VALUES FROM APIS TO VIEW ELEMENTS HERE"
        console.log "DETECT AN UP, DOWN, LEFT, RIGHT, FORWARD, BACK gesture"

        

#gesturepad
    #gesture-square
        #screen
    %h1#gesture &lt;&lt;GESTURE DETECTED&gt;&gt;
    %h2#orientation ATTACH GYROSCOPE DATA TO ME
    %h3#acceleration ATTACH ACCELEROMETER DATA TO ME

    
// IGNORE, BUT KEEP THIS LINE (Back button)   
= render :partial => "application/back_to_root"
    
:scss
    $gesturepad-bg: desaturate(green, 70%);
    $gesture-square: lighten($gesturepad-bg, 70%);
    html, body{ overflow: none;}
    #gesturepad{
        height: 100%;
        width: 100%;
        overflow: none;
        color: white;
        font-family: Avenir, sans-serif;
        font-size: 4em;
        text-align: center;
            
        background: $gesturepad-bg;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        #gesture-square{
            width: 150px;
            height: 200px;
            background: $gesture-square;
            transition: transform 2s;
            #screen{
                width: calc(100% - 20px);
                height: calc(100% - 30px);
                background: darken($gesture-square, 80%);
                margin: 10px;
                margin-bottom: 20px;
            }
        }
    }
    

app/views/magic/home.html.haml
%h1 Magic#home
%p Find me in app/views/magic/home.html.haml

app/views/magic/light.html.haml
#instadesktop
    #webcam-feed.col-xs-12.col-sm-6
        %span WEBCAM FEED HERE
    #snapshot.col-xs-12.col-sm-6
        %h1 EVENT: LIGHTS OFF
        %h2 AVERAGE LIGHT VALUE HERE
    
// IGNORE, BUT KEEP THIS LINE (Back button)   
= render :partial => "application/back_to_root"
:scss
    #instadesktop{
        height: 100%;
        width: 100%;
        color: white;
        font-family: Avenir, sans-serif;
        font-size: 4em;
        text-align: center;
            
        #webcam-feed{
            height: 100%;
            background: desaturate(blue, 80%);
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            button{
                position: absolute;
                bottom: 0;
            }
        }
        #snapshot{
            height: 100%;
            background: desaturate(red, 80%);
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            position: relative;
        }
    }
    #back-button{
        position: absolute;
        z-index: 100;
        top: 15px;
        left: 15px;
    }

app/views/magic/mirror_portal.html.haml
:coffeescript
    $ ->
        console.log "WEBSOCKET TO MIRROR HERE"
        console.log "WEBSOCKET HANDLER FROM MIRROR HERE"
        
        

#wand
    %h1 I am the mirror

    
// IGNORE, BUT KEEP THIS LINE (Back button)   
= render :partial => "application/back_to_root"
    
:scss
    $bg: desaturate(purple, 70%);
    html, body{ overflow: none;}
    #wand{
        height: 100%;
        width: 100%;
        overflow: none;
        color: white;
        font-family: Avenir, sans-serif;
        font-size: 4em;
        text-align: center;
            
        background: $bg;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
    }
    

app/views/magic/sensing.html.haml
:coffeescript
    $ ->
        console.log "BIND VALUES FROM APIS TO VIEW ELEMENTS HERE"
        

#gesturepad
    #gesture-square
        #screen
    %h2#orientation ATTACH GYROSCOPE DATA TO ME
    %h3#acceleration ATTACH ACCELEROMETER DATA TO ME

    
// IGNORE, BUT KEEP THIS LINE (Back button)   
= render :partial => "application/back_to_root"
    
:scss
    $gesturepad-bg: desaturate(green, 70%);
    $gesture-square: lighten($gesturepad-bg, 70%);
    html, body{ overflow: none;}
    #gesturepad{
        height: 100%;
        width: 100%;
        overflow: none;
        color: white;
        font-family: Avenir, sans-serif;
        font-size: 4em;
        text-align: center;
            
        background: $gesturepad-bg;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        #gesture-square{
            width: 150px;
            height: 200px;
            background: $gesture-square;
            transition: transform 2s;
            #screen{
                width: calc(100% - 20px);
                height: calc(100% - 30px);
                background: darken($gesture-square, 80%);
                margin: 10px;
                margin-bottom: 20px;
            }
        }
    }
    

app/views/magic/wand_portal.haml
:coffeescript
    $ ->
        console.log "WEBSOCKET TO MIRROR HERE"
        console.log "WEBSOCKET HANDLER FROM MIRROR HERE"
        
        

#wand
    %h1 I am the wand

    
// IGNORE, BUT KEEP THIS LINE (Back button)   
= render :partial => "application/back_to_root"
    
:scss
    $bg: desaturate(purple, 70%);
    html, body{ overflow: none;}
    #wand{
        height: 100%;
        width: 100%;
        overflow: none;
        color: white;
        font-family: Avenir, sans-serif;
        font-size: 4em;
        text-align: center;
            
        background: $bg;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
    }
    

app/views/tab/wand.html.haml
#wand.col-xs-12
    %span MAGIC WAND
      
// IGNORE, BUT KEEP THIS LINE (Back button)   
= render :partial => "application/back_to_root"

:scss
    #wand{
        height: 100%;
        width: 100%;
        color: white;
        font-family: Avenir, sans-serif;
        font-size: 4em;
        text-align: center;
        
        background: desaturate(orange, 80%);
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
       
    }
   